FROM namely/protoc:latest

WORKDIR /proto
COPY proto/ ./proto/

RUN mkdir -p gen/go gen/python gen/scala

# Generate Go stubs
RUN protoc --proto_path=proto \
  --go_out=gen/go --go_opt=paths=source_relative \
  --go-grpc_out=gen/go --go-grpc_opt=paths=source_relative \
  proto/polymas/v1/*.proto

# Generate Python stubs
RUN protoc --proto_path=proto \
  --python_out=gen/python --python_opt=paths=source_relative \
  --grpc_python_out=gen/python \
  proto/polymas/v1/*.proto

CMD ["cp", "-r", "/proto/gen/", "/proto/gen-out/"]
